# Generated by Django 5.1.5 on 2025-01-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='weekly_update_avg_rating',
            new_name='avg_rating_weekly',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='weekly_updated_number_of_ratings',
            new_name='number_of_ratings_weekly',
        ),
    ]
